name: x

on:
  push:
    branches: [main]
  workflow_dispatch:

  # Cancel in-progress runs on new push to the same branch/PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: go-faster/x/.github/workflows/test.yml@main
    permissions:
      contents: read
  cover:
    uses: go-faster/x/.github/workflows/cover.yml@main
    permissions:
      contents: read
  lint:
    uses: go-faster/x/.github/workflows/lint.yml@main
    permissions:
      contents: read
